//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VideoGamesMgmt
{
    using System;
    using System.Collections.Generic;
    
    public partial class categoriesmaster
    {
        public categoriesmaster()
        {
            this.videogamescategories = new HashSet<videogamescategory>();
        }
    
        public int Category_ID { get; set; }
        public string Category_Name { get; set; }
    
        public virtual ICollection<videogamescategory> videogamescategories { get; set; }
    }
}
