//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VideoGamesMgmt
{
    using System;
    using System.Collections.Generic;
    
    public partial class console
    {
        public console()
        {
            this.videogamesconsoles = new HashSet<videogamesconsole>();
        }
    
        public int Console_ID { get; set; }
        public string Console_Name { get; set; }
        public string Console_Type { get; set; }
    
        public virtual ICollection<videogamesconsole> videogamesconsoles { get; set; }
    }
}
