//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VideoGamesMgmt
{
    using System;
    using System.Collections.Generic;
    
    public partial class videogame
    {
        public videogame()
        {
            this.videogamescategories = new HashSet<videogamescategory>();
            this.videogamesconsoles = new HashSet<videogamesconsole>();
        }
    
        public int Game_ID { get; set; }
        public string Game_Name { get; set; }
        public string Game_Desc { get; set; }
        public string Game_Title { get; set; }
    
        public virtual ICollection<videogamescategory> videogamescategories { get; set; }
        public virtual ICollection<videogamesconsole> videogamesconsoles { get; set; }
    }
}
