//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VideoGamesMgmt
{
    using System;
    using System.Collections.Generic;
    
    public partial class videogamesconsole
    {
        public videogamesconsole()
        {
            this.gamecontents = new HashSet<gamecontent>();
        }
    
        public int VGCon_ID { get; set; }
        public Nullable<int> VGCon_Game_ID { get; set; }
        public Nullable<int> VGCon_Console_ID { get; set; }
    
        public virtual console console { get; set; }
        public virtual ICollection<gamecontent> gamecontents { get; set; }
        public virtual videogame videogame { get; set; }
    }
}
