//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VideoGamesMgmt
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class videogamesmgmtEntities : DbContext
    {
        public videogamesmgmtEntities()
            : base("name=videogamesmgmtEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<categoriesmaster> categoriesmasters { get; set; }
        public virtual DbSet<conditionsmaster> conditionsmasters { get; set; }
        public virtual DbSet<console> consoles { get; set; }
        public virtual DbSet<gamecomleteness> gamecomletenesses { get; set; }
        public virtual DbSet<gamecontent> gamecontents { get; set; }
        public virtual DbSet<videogamescategory> videogamescategories { get; set; }
        public virtual DbSet<videogamesconsole> videogamesconsoles { get; set; }
        public virtual DbSet<videogame> videogames { get; set; }
    }
}
